
- name: Deploy Java EE App
  hosts: localhost
  tasks:
    - name: Copy WAR file
      copy:
        src: "{{ jenkins_workspace }}/target/simple-javaee-app.war"
        dest: "/var/lib/tomcat9/webapps/"
        owner: tomcat
        group: tomcat
        mode: '0644'
    - name: Restart Tomcat
      service:
        name: tomcat9
        state: restarted
