---
- name: Deploy Java EE App
  hosts: localhost
  become: yes
  tasks:
    - name: Copy WAR file into Tomcat
      copy:
        src: "{{ jenkins_workspace }}/target/simple-javaee-app.war"
        dest: "/var/lib/tomcat9/webapps/simple-javaee-app.war"
        owner: tomcat
        group: tomcat
        mode: '0644'

    - name: Restart Tomcat
      service:
        name: tomcat9
        state: restarted
